# Analysis of the Amazon UK Price Prediction dataset II

In [1]:
import pandas as pd

df = pd.read_csv("amz_uk_price_prediction_dataset.csv")

## Initial Assessment

In [2]:
df.shape

(2443651, 9)

In [3]:
df.head()

,uid,asin,title,stars,reviews,price,isBestSeller,boughtInLastMonth,category
0,1,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",4.7,15308,21.99,False,0,Hi-Fi Speakers
1,2,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",4.7,98099,23.99,True,0,Hi-Fi Speakers
2,3,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",4.7,15308,21.99,False,0,Hi-Fi Speakers
3,4,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",4.7,7205,31.99,False,0,Hi-Fi Speakers
4,5,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,4.6,1881,17.99,False,0,Hi-Fi Speakers

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2443651 entries, 0 to 2443650
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   uid                int64
 1   asin               str
 2   title              str
 3   stars              float64
 4   reviews            int64
 5   price              float64
 6   isBestSeller       bool
 7   boughtInLastMonth  int64
 8   category           str
dtypes: bool(1), float64(2), int64(3), str(3)
memory usage: 151.5 MB

In [ ]:
df.describe()

,uid,stars,reviews,price,boughtInLastMonth
count,2.443651e+06,2.443651e+06,2.443651e+06,2.443651e+06,2.443651e+06
mean,1.370545e+06,2.152836e+00,4.806278e+02,8.924381e+01,2.589699e+01
std,8.160562e+05,2.194865e+00,5.944124e+03,3.456089e+02,2.404837e+02
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.589215e+05,0.000000e+00,0.000000e+00,9.990000e+00,0.000000e+00
50%,1.349029e+06,0.000000e+00,0.000000e+00,1.909000e+01,0.000000e+00
75%,2.060686e+06,4.400000e+00,5.900000e+01,4.599000e+01,0.000000e+00
max,2.828593e+06,5.000000e+00,1.356658e+06,1.000000e+05,5.000000e+04

In [ ]:
df.isna().sum()

uid                  0
asin                 0
title                0
stars                0
reviews              0
price                0
isBestSeller         0
boughtInLastMonth    0
category             0
dtype: int64

## Part 1: Analyzing Best-Seller Trends Across Product Categories
*Objective*: Understand the relationship between product categories and their best-seller status.

1. Create a crosstab between the product ```category``` and the ```isBestSeller``` status.
2. Are there categories where being a best-seller is more prevalent? (Hint: one option is to calculate the proportion of best-sellers for each category and then sort the categories based on this proportion in descending order.)
3. Conduct a Chi-square test to determine if the best-seller distribution is independent of the product category.
4. Compute Cramér's V to understand the strength of association between best-seller status and category.
5. Visualize the relationship between product categories and the best-seller status using a stacked bar chart.

In [ ]:
# code

## Part 2: Exploring Product Prices and Ratings Across Categories and Brands

*Objective*: Investigate how different product categories influence product prices.

*Preliminary Step*: Remove outliers in product prices.
For this purpose, we can use the IQR (Interquartile Range) method. Products priced below the first quartile minus 1.5 times the IQR or above the third quartile plus 1.5 times the IQR will be considered outliers and removed from the dataset. The next steps will be done with the dataframe without outliers.
Hint: you can check the last Check For Understanding at the end of the lesson EDA Bivariate Analysis for a hint on how to do this.

1. Use a violin plot to visualize the distribution of ```price``` across different product ```categories```. Filter out the top 20 categories based on count for better visualization.
2. Which product category tends to have the highest median price? Don't filter here by top categories.
3. Create a bar chart comparing the average price of products for the top 10 product categories (based on count).
4. Which product category commands the highest average price? Don't filter here by top categories.
5. Visualize the distribution of product ```ratings``` based on their ```category``` using side-by-side box plots. Filter out the top 10 categories based on count for better visualization.
6. Which category tends to receive the highest median rating from customers? Don't filter here by top categories.

In [ ]:
# code

## Part 3: Investigating the Interplay Between Product Prices and Ratings

*Objective*: Analyze how product ratings (```stars```) correlate with product prices.

1. Calculate the correlation coefficient between ```price``` and ```stars```.
2. Is there a significant correlation between product price and its rating?
3. Use a scatter plot to visualize the relationship between product rating and price. What patterns can you observe?
4. Use a correlation heatmap to visualize correlations between all numerical variables.
5. Examine if product prices typically follow a normal distribution using a QQ plot.

In [ ]:
# code

##